[build]
  # Directory to change to before starting a build
  base = "frontend/"
  
  # Directory with the deployable files
  publish = "build/"
  
  # Default build command
  command = "CI=false npm run build"

[build.environment]
  # Node version for build
  NODE_VERSION = "18"
  
  # Skip source maps for production
  GENERATE_SOURCEMAP = "false"
  
  # Don't treat warnings as errors
  CI = "false"

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://tic-tac-toe-uf5h.onrender.com wss://tic-tac-toe-uf5h.onrender.com https://*.google.com https://*.facebook.com;"

# Cache static assets for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache index.html for shorter time
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
